# Generated by Django 4.2.7 on 2026-03-06 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneUsageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone_detections/')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person_count', models.IntegerField(default=0)),
                ('phone_count', models.IntegerField(default=0)),
                ('phone_users_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Phone Usage Detection',
                'verbose_name_plural': 'Phone Usage Detections',
                'ordering': ['-detected_at'],
            },
        ),
    ]
